# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 334)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier10 BT")
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"    border: 1px solid black;\n"
"    background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeStarted = QtWidgets.QLCDNumber(parent=self.frame)
        self.timeStarted.setMinimumSize(QtCore.QSize(175, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.timeStarted.setFont(font)
        self.timeStarted.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.timeStarted.setStyleSheet("")
        self.timeStarted.setObjectName("timeStarted")
        self.gridLayout_2.addWidget(self.timeStarted, 0, 0, 1, 1)
        self.currentTime = QtWidgets.QLCDNumber(parent=self.frame)
        self.currentTime.setMinimumSize(QtCore.QSize(175, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.currentTime.setFont(font)
        self.currentTime.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.currentTime.setStyleSheet("")
        self.currentTime.setObjectName("currentTime")
        self.gridLayout_2.addWidget(self.currentTime, 0, 1, 1, 2)
        self.timeSpent = QtWidgets.QLCDNumber(parent=self.frame)
        self.timeSpent.setMinimumSize(QtCore.QSize(175, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.timeSpent.setFont(font)
        self.timeSpent.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.timeSpent.setStyleSheet("")
        self.timeSpent.setObjectName("timeSpent")
        self.gridLayout_2.addWidget(self.timeSpent, 1, 0, 1, 1)
        self.logMessage = QtWidgets.QTextEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.logMessage.setFont(font)
        self.logMessage.setStyleSheet("QTextEdit{\n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"}")
        self.logMessage.setObjectName("logMessage")
        self.gridLayout_2.addWidget(self.logMessage, 2, 0, 1, 2)
        self.submitButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitButton.sizePolicy().hasHeightForWidth())
        self.submitButton.setSizePolicy(sizePolicy)
        self.submitButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        self.submitButton.setFont(font)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.submitButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 1px solid blue;\n"
"    border-radius: 20px;\n"
"    padding: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: transparent;\n"
"    border: 1px solid red;\n"
"    border-radius: 20px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 255, 0, 60);\n"
"    border: 2px solid black;\n"
"    border-radius: 20px;\n"
"    font: 15pt \"Georgia\";\n"
"    padding: 15px;\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    background-color: rgba(212, 208, 200, 80);\n"
"    border: 1px solid grey;\n"
"    border-radius: 20px;\n"
"    color: grey;\n"
"}")
        self.submitButton.setObjectName("submitButton")
        self.gridLayout_2.addWidget(self.submitButton, 2, 2, 1, 1)
        self.leaveTimeEdit = QtWidgets.QTimeEdit(parent=self.frame)
        self.leaveTimeEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.leaveTimeEdit.setFont(font)
        self.leaveTimeEdit.setStyleSheet("")
        self.leaveTimeEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.leaveTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.leaveTimeEdit.setCalendarPopup(False)
        self.leaveTimeEdit.setObjectName("leaveTimeEdit")
        self.gridLayout_2.addWidget(self.leaveTimeEdit, 3, 0, 1, 1)
        self.countdown = QtWidgets.QLCDNumber(parent=self.frame)
        self.countdown.setMinimumSize(QtCore.QSize(0, 30))
        self.countdown.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.countdown.setStyleSheet("")
        self.countdown.setObjectName("countdown")
        self.gridLayout_2.addWidget(self.countdown, 3, 1, 1, 2)
        self.timeRemaining = QtWidgets.QLCDNumber(parent=self.frame)
        self.timeRemaining.setMinimumSize(QtCore.QSize(175, 30))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.timeRemaining.setFont(font)
        self.timeRemaining.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.timeRemaining.setStyleSheet("")
        self.timeRemaining.setObjectName("timeRemaining")
        self.gridLayout_2.addWidget(self.timeRemaining, 1, 1, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.exportToExcelAction = QtGui.QAction(parent=MainWindow)
        self.exportToExcelAction.setObjectName("exportToExcelAction")
        self.fetchDescriptionAction = QtGui.QAction(parent=MainWindow)
        self.fetchDescriptionAction.setObjectName("fetchDescriptionAction")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeStarted.setToolTip(_translate("MainWindow", "Time Logged In"))
        self.currentTime.setToolTip(_translate("MainWindow", "Clock Time"))
        self.timeSpent.setToolTip(_translate("MainWindow", "Time Elapsed"))
        self.submitButton.setText(_translate("MainWindow", "OK"))
        self.leaveTimeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.countdown.setToolTip(_translate("MainWindow", "Time Remaining for Desired"))
        self.timeRemaining.setToolTip(_translate("MainWindow", "Time Remaining for Ideal"))
        self.exportToExcelAction.setText(_translate("MainWindow", "Export to Excel"))
        self.fetchDescriptionAction.setText(_translate("MainWindow", "Fetch Description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
